# Generated by Django 4.0.5 on 2022-07-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la especie')),
                ('nombreEspecie', models.CharField(max_length=30, verbose_name='Nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitaciones'], [4, 'Solicitud']])),
                ('motivo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='numero de producto')),
                ('precio', models.IntegerField(max_length=50, verbose_name='Precio ')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=30, verbose_name='marca')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especie')),
            ],
        ),
    ]
